import fs from "node:fs";
import path from "node:path";
import { admitRealPilotRequest } from "../../src/real-pilot-admission.mjs";
import { commitPilotAuthorization, preparePilotAuthorization } from "../../src/pilot-authorization.mjs";
import { preparePendingWorkspace } from "../../src/coordinator.mjs";
import { createLocalCheckpoint } from "../../src/local-checkpoint.mjs";
import { readState } from "../../src/local-store.mjs";
import { finishRole, startRole } from "../../src/role-timing.mjs";
import { submitRoleResult } from "../../src/result-submission.mjs";
import { resultContextForTask } from "../../src/validate.mjs";
import { attestedValidationEntries } from "../../src/validation-evidence.mjs";
import { activationFixture } from "./activation-fixture.mjs";

export function prepareAcceptedActivation(prefix = "accepted") {
  const fixture = activationFixture(prefix); let tick = Date.parse("2026-09-22T08:00:00.000Z"); const now = () => new Date(tick += 1000).toISOString();
  const proposal = preparePilotAuthorization({ statePath: fixture.statePath, request: fixture.request, humanApproval: fixture.approval, controllerRoot: fixture.controller.root, now: now() }); commitPilotAuthorization({ statePath: fixture.statePath, proposal, confirmation: `CONFIRM ${proposal.grant.authorizationDigest}` }); admitRealPilotRequest({ statePath: fixture.statePath, request: fixture.request, controllerRoot: fixture.controller.root, now: now() });
  const ownerId = "trusted-operator"; const ownerGeneration = 1; const task = () => { const state = readState(fixture.statePath); return state.tasks.find((item) => item.taskId === state.pendingTaskId); };
  const completeTiming = (current) => { startRole({ statePath: fixture.statePath, ownerId, ownerGeneration, taskId: current.taskId, now: now() }); finishRole({ statePath: fixture.statePath, ownerId, ownerGeneration, taskId: current.taskId, now: now() }); };
  const result = (current, payload) => ({ schemaVersion: 2, taskDigest: current.taskDigest, context: resultContextForTask(current), outcome: "COMPLETED", payload });
  let current = task(); completeTiming(current); submitRoleResult({ statePath: fixture.statePath, ownerId, ownerGeneration, result: result(current, { goal: "Create the authorized fictional offline guide.", scope: current.authorization.scope, allowedChanges: current.authorization.allowedChanges, forbiddenChanges: current.authorization.forbiddenChanges, acceptanceCriteria: current.authorization.acceptanceCriteria, validationRequirements: current.authorization.validationRequirements, risks: [], rationale: "Bounded human-assisted plan.", resolvesFindingIds: [] }), now: now() });
  current = task(); preparePendingWorkspace({ statePath: fixture.statePath, ownerId, ownerGeneration, taskId: current.taskId, runtimeRoot: path.join(fixture.root, "workspace-runtime"), now: now() }); current = task(); completeTiming(current); const stateWithWorkspace = readState(fixture.statePath); const builderWorkspace = stateWithWorkspace.workspaces.find((item) => item.taskId === current.taskId); const guide = path.join(builderWorkspace.root, "docs/learning/offline-fixture-reading.md"); fs.mkdirSync(path.dirname(guide), { recursive: true }); fs.writeFileSync(guide, "# Fictional Offline Fixture Reading\n\nThis fictional offline non-production guide is non-governance and non-operational. Compare stable record identifiers and sources to identify a conceptual duplicate without any live service.\n"); const checkpoint = createLocalCheckpoint({ statePath: fixture.statePath, ownerId, ownerGeneration, taskId: current.taskId, now: now() }).receipt; let state = readState(fixture.statePath); submitRoleResult({ statePath: fixture.statePath, ownerId, ownerGeneration, result: result(current, { candidateCommit: checkpoint.candidateCommit, parentCommit: checkpoint.parentCommit, treeId: checkpoint.treeId, changedFiles: [{ path: "docs/learning/offline-fixture-reading.md", operation: "ADD", mode: "100644" }], validation: attestedValidationEntries(state, current, "PASS"), deviations: [], blockers: [] }), now: now() });
  current = task(); preparePendingWorkspace({ statePath: fixture.statePath, ownerId, ownerGeneration, taskId: current.taskId, runtimeRoot: path.join(fixture.root, "workspace-runtime"), now: now() }); current = task(); completeTiming(current); state = readState(fixture.statePath); submitRoleResult({ statePath: fixture.statePath, ownerId, ownerGeneration, result: result(current, { reviewedCommit: checkpoint.candidateCommit, reviewState: "PASS", findings: [], requiredChanges: [], recommendations: [], validation: attestedValidationEntries(state, current, "PASS") }), now: now() });
  current = task(); completeTiming(current); const beforeDecision = readState(fixture.statePath); submitRoleResult({ statePath: fixture.statePath, ownerId, ownerGeneration, result: result(current, { reviewedCommit: checkpoint.candidateCommit, analystResultDigest: beforeDecision.cycles[0].analystResultDigest, decision: "ACCEPT", rationale: "Exact candidate and successful validation evidence accepted.", recommendationDispositions: [] }), now: now() });
  return { ...fixture, proposal, cycleId: proposal.grant.cycleId, candidateCommit: checkpoint.candidateCommit, ownerId, ownerGeneration, nextTime: now };
}
